appleboy/CodeGPT

- cmd/commit.go
- cmd/config.go
- openai/openai.go
- Add `net/http` and `net/url` packages to `commit.go`
- Add `httpClient` and `proxy` variables to `commit.go`
- Add `proxy` flag to `config.go`
- Add `httpClient` argument to `New` function in `openai/openai.go`
- Add conditional assignment to `cfg.HTTPClient` in `New` function of `openai/openai.go`
fix https://github.com/appleboy/CodeGPT/issues/1
> chore(openai): Add support for HTTP proxy configuration.

- cmd/commit.go
- git/git.go
- prompt/prompt.go
- prompt/templates/conventional_commit.tmpl
- Add support for conventional commits
- Add a new template for conventional commits
- Update the `prompt.go` file to include the new template
- Remove the `ignoreLists` field from the `Command` struct in `git.go`
fix #9
> feat: Add support for conventional commits and templates

- cmd/commit.go
- git/git.go
- git/templates/prepare-commit-msg
- Add a `disableAutoCommit` flag to the `commit` command
- Add the `--no-verify` flag to the `commit` command
- Modify the `prepare-commit-msg` file to use the `--disbaleCommit` flag when invoking the `codegpt commit` command
fix #12
> chore: Add option to disable automatic commits and skip verification.

- cmd/commit.go
- git/git.go
- go.mod
- go.sum
- Add `go.mod` to the excluded files when diffing
- Lowercase the first character of the first word of the commit message and remove the last period
fix #17
> style: improve consistency and clarity of commit messages

- cmd/commit.go
- cmd/config.go
- commitlint.config.js
- git/git.go
- git/options.go
- Add a `diff_unified` option to generate diffs with a specific number of lines of context.
- Modify `git.New()` to accept options to configure the `diff_unified` value.
- Add a new file `git/options.go` that defines an `Option` interface and a `WithDiffUnified` function to set the `diff_unified` value.
fix #21 
fix #6
> feat: add option to configure number of context lines in diffs

- cmd/commit.go
- cmd/config.go
- git/git.go
- git/options.go
- Add a `excludeList` flag to `config.go` and `commit.go`
- Implement `WithExcludeList` option in `options.go`
- Use `excludeList` in `excludeFiles` function in `git.go`
fix https://github.com/appleboy/CodeGPT/issues/7
> feat: add excludeList flag to git operations

- README.md
- Add instructions for installing `codegpt` via Homebrew on MacOS
- Remove irrelevant context lines
fix https://github.com/appleboy/CodeGPT/issues/8
> docs: improve installation instructions for codegpt on MacOS via Homebrew

- cmd/cmd.go
- Added import for the "strings" package
- Defined a replacer for "-" and "." with "_" in variable "replacer"
- Added a call to "SetEnvKeyReplacer" for the "viper" object in the "initConfig" function.
fix https://github.com/appleboy/CodeGPT/issues/16
> refactor: replace hyphens and dots in environment variable keys

- git/git.go
- Add the "--signoff" flag to the git commit command in line 87 of git.go.
fix #29
> chore: add --signoff flag to git commit command

- cmd/commit.go
- cmd/config.go
- util/template.go
- Add `template_file` and `template_string` flags to `commit` command
- Implement `NewTemplateByString` function for creating templates from string input
fix #31
> feat: add template options to commit command

- cmd/commit.go
- git/git.go
- git/options.go
- Add a `--amend` boolean flag to `commitCmd` in `cmd/commit.go`
- Add an `--amend` boolean flag to `Command` in `git/git.go`
- Add `WithEnableAmend` option to `WithAmend` in `git/options.go`
fix #32
> feat: add amend functionality to commit command

- openai/openai.go
- Add four new models to the `modelMaps` map in `openai.go`
fix #37
> feat: add new models to modelMaps map in openai.go file

- README.md
- Fix a typo in the README.md file message
- Correct the flag name from `--anmed` to `--amend`
> docs: correct flag name in README

- go.mod
- go.sum
- openai/openai.go
- Update the version of `go-openai` from `v1.5.4` to `v1.5.7` in `go.mod`
- Update the version of `go-isatty` from `v0.0.17` to `v0.0.18` in `go.mod`
- Add support for new OpenAI API models in `openai.go`
Support `openai.GPT4`
fix #42
> chore: update OpenAI dependencies and add new models support

- cmd/review.go
- prompt/prompt.go
- prompt/templates/code_review_file_diff.tmpl
- Add a new file `cmd/review.go`
- Add package imports for `github.com/appleboy/CodeGPT/git`, `github.com/appleboy/CodeGPT/openai`, `github.com/appleboy/CodeGPT/prompt`, `github.com/appleboy/CodeGPT/util`, `github.com/fatih/color`, `github.com/spf13/cobra`, and `github.com/spf13/viper`
- Add command line flags `diff_unified`, `model`, `lang`, `exclude_list`, and `amend` to `reviewCmd`
- Move initialization of command line flags to `init()` function
- Set up a `git` object with options, and call `g.DiffFiles()` to get the file diff data
- Set up an `openai` client with options, and call `client.Completion()` with the file diff data to get the AI-generated code review summary
- Add a new file `prompt/prompt.go
fix #45
> feat: add code review command to CLI

- cmd/commit.go
- commitlint.config.js
- git/git.go
- Change the default value of the &#34;file&#34; flag to an empty string
- Add a &#34;topLevel&#34; function to the Git command struct, which returns the top-level directory of the working tree
- Add a &#34;Commit&#34; function to the Git command struct, which writes a commit with the given message and returns the commit hash
fix #49
> feat: update Git command struct with new functions

- .github/workflows/docker.yml
- Makefile
- docker/Dockerfile
- Add a Dockerfile for building a Docker image
- Add a GitHub Actions workflow for building and pushing Docker image to Docker Hub and GitHub Container Registry
- Modify Makefile to include build targets for different architecture
> build: add Docker support with CI/CD pipeline

- cmd/commit.go
- cmd/review.go
- openai/openai.go
- openai/options.go
- openai/options_test.go
- Update `cmd/commit.go` and `cmd/review.go` to use `openai.WithProvider` instead of `openai.WithServiceProvider`
- Refactor `openai.New` to move the initialization of `cfg` to `newConfig` function
- Add `openai.WithProvider` to `openai/options.go` to set the `provider` variable
- Add `openai/options_test.go` to test the `config.vaild()` function
> refactor: OpenAI provider initialization and testing

- cmd/commit.go
- openai/options_test.go
- Add unescaping of HTML entities in commit message
- Replace one test case with two for `config_valid` function in `openai/options_test.go`
fix #62
> fix: improve code reliability and maintainability

- openai/openai.go
- rename var '`proxy`' to '`proxyURL`' to avoid collides with an imported package name
> style: variable 'proxy' collides with imported package name 

- cmd/commit.go
- git/git.go
git worktree's COMMIT_EDITMSG are stored in
repo/.git/worktrees/branch/COMMIT_EDITMSG
We should use `git rev-parse --git-dir` to get the worktree's git direcotry, and find the COMMIT_EDITMSG.
Hope this patch can fix #49.
> fix: fix COMMIT_EDITMSG of worktree missing bug

- README.md
- Replace "openai.lang" with "output.lang" in README.md
fix #75
> docs: improve API usage, testing, and documentation

- go.mod
- go.sum
- openai/openai.go
- Update go-openai dependency from v1.9.3 to v1.9.4
- Refactor defaultAzureConfig initialization with AzureModelMapperFunc in New function
> chore: upgrade go-openai from v1.9.3 to v1.9.4

- cmd/commit.go
- util/template_test.go
- util/util.go
- util/util_test.go
- Add `templateVars` flag to `commitCmd`
- Implement `ConvertToMap` function to convert a slice of strings to a map
- Add test for `NewTemplateByStringWithCustomVars`
- Add test for `ConvertToMap`
ref #72
> feat: improve template handling and test coverage

- README.md
- Add instructions for adding custom variables to git commit message template
- Explain usage of `--template_vars` and `--template_vars_file` parameters
- Provide examples of custom variable usage and template_vars_file format
fix #72
> docs: enhance commit message customization and documentation

- cmd/config.go
- Fixed an issue in the config command where the `viper.BindPFlag` error caused the parsing of `git.exclude_list vendor/*,go.sum,**/code_gen.go` as `"exclude_list":"vendor/*,go.sum,**/code_gen.go"` and writing it to `.codegpt.yaml`, resulting in the global exclude_list being ineffective.(https://github.com/spf13/viper/issues/380)
- Fixed a typo in the comments: `srvice` -> `service`.
> refactor: refactor exclude_list flag to accept comma-separated values

- cmd/commit.go
- cmd/config.go
- cmd/review.go
- openai/openai.go
- openai/options.go
- Add `openai.WithApiVersion(viper.GetString("openai.api_version"))` to `cmd/commit.go`
- Add `openai.api_version` to `cmd/config.go`
- Add `openai.WithApiVersion(viper.GetString("openai.api_version"))` to `cmd/review.go`
- Add `cfg.apiVersion` to `openai/openai.go`
- Add `WithApiVersion(apiVersion string)` to `openai/options.go`
fix #94
> feat(model): add support for OpenAI API version configuration

- cmd/hepler.go
fix the default value (300) of maxTokens in reviewCmd, as it causes a bug in commitCmd where the max_tokens is fixed at 300
> fix: fix the max_tokens is fixed at 300 in commitCmd

- cmd/commit.go
- openai/func.go
- openai/func_test.go
- openai/openai.go
fix #96 
fix https://github.com/appleboy/CodeGPT/issues/91
- Modify `cmd/commit.go`
- Change the `client.Completion` function call to `client.CreateFunctionCall`
- Update the assignment of `data[prompt.SummarizePrefixKey]`
- Add a new variable `summaryPrix` and assign it based on the choices in `resp`
- Add a new file `openai/func.go`
- Add a new file `openai/func_test.go`
- Modify `openai/openai.go`
- Add a new function `CreateFunctionCall`
> feat: refactor completion function and add CreateFunctionCall function

- cmd/commit.go
- openai/openai.go
- Modify the `commit.go` file:
- Add a new variable `summaryPrix` and initialize it as an empty string
- If `client.AllowFuncCall()` is true, make a function call to `openai.SummaryPrefixFunc` and assign the response to `resp`
- If `resp.Choices` has more than 0 elements, extract the prefix from the arguments and assign it to `summaryPrix`
- Set `data[prompt.SummarizePrefixKey]` to `summaryPrix`
- If `client.AllowFuncCall()` is false, make a completion call and assign the response to `resp`
- Trim the content of `resp` and assign it to `summaryPrix`
- Set `data[prompt.SummarizePrefixKey]` to `summaryPrix`
- Modify the `openai.go` file:
- Add a new function `AllowFuncCall()` that returns true if the model supports function calls
ref: #91
> refactor: add support for function calls in summarization

- README.md
- Changed displayed version from v0.1.6 to v0.4.3.
- Perhaps "v0.4.x" for future references? Although, maybe more convenient but less pretty.
> chore: update CodeGPT version in README.md

- cmd/commit.go
- cmd/config.go
- cmd/review.go
- openai/openai.go
- openai/options.go
- Add `openai.WithTopP(float32(viper.GetFloat64("openai.top_p")))` to `commit.go`
- Add `openai.WithFrequencyPenalty(float32(viper.GetFloat64("openai.frequency_penalty")))` to `commit.go`
- Add `openai.WithPresencePenalty(float32(viper.GetFloat64("openai.presence_penalty")))` to `commit.go`
- Add `openai.top_p` to `availableKeys` in `config.go`
- Add `openai.frequency_penalty` to `availableKeys` in `config.go`
- Add `openai.presence_penalty` to `availableKeys` in `config.go`
- Add `configCmd.PersistentFlags().Float32P("top_p", "", 1.0, "An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.")` to `config.go`
- …
> chore: add OpenAI configuration options to commit command

- cmd/commit.go
- cmd/config_list.go
- cmd/config_set.go
- Increase the default timeout to `30` seconds
- Change the default timeout to `30` seconds in the `commitCmd` function
- Change the `availableKeys` map value for `openai.timeout` from `http timeout` to `request timeout`
- Remove the import of `time` in the `cmd/config_set.go` file
- Change the default timeout to `30` seconds in the `configSetCmd` function
fixed https://github.com/appleboy/CodeGPT/pull/92
> chore(timeout): update default timeout to 30 seconds across files

- README.md
- groq/model.go
- openai/openai.go
Here's a summary of the git diff:
* Changed the name of the `model.go` file to `groq/model.go`
* Added a new package called `groq`
* Added a new type called `Model` that has three string values: `LLaMA270bChat`, `Mixtral8x7bInstructV01`, and `Gemma7bIt`
* Added a function called `GetModel` that takes a `Model` value and returns a string representing the model name
* Added a function called `IsValid` that takes a `Model` value and returns a boolean indicating whether the model is valid
* Added a map called `model` that maps the three `Model` values to their corresponding string names
* Changed the `README.md` file to include information about the new `groq` package and the `Model` type
Overall, it seems like this commit adds a new package called `groq` that contains a new type called …
> feat(model): Introduce Groq package with Model type and related functions

- openai/openai.go
Add support for function calling in OpenAI API and enable parallel function calls in select models
- Add support for function calling in OpenAI API
- Add support for parallel function calls in certain models
- Allow function calling in the following models: gpt-4, gpt-4-turbo-preview, gpt-4-0125-preview, gpt-4-1106-preview, gpt-4-0613, gpt-3.5-turbo, gpt-3.5-turbo-0125, gpt-3.5-turbo-1106
- Add a check for the model version to allow function calling
- Change the client struct to include a new field for the model version
- Update the `allowFuncCall` function to check the model version and return true if the model supports function calling
> feat(func): support for function calling in OpenAI API

- git/templates/prepare-commit-msg
This is a very simple feature that, if you `codegpt hook install` and later on, you want to use `git commit -m <custom_message>` would use that specified message. I think this is useful especially for automated deployments and releases where the  <custom_message> is really important to not change.
> feat(git): don't use codegpt if user supplies message with `git commit -m`

- README.md
- groq/model.go
- openai/openai.go
- Update model references from `LLaMA2-70b-chat`, `Mixtral-8x7b-Instruct-v0.1`, and `Gemma-7b-it` to `llama3-8b-8192`, `llama3-70b-8192`, `mixtral-8x7b-32768`, and `gemma-7b-it` in README.md
- Replace old model constants with new ones in `groq/model.go`
- Remove deprecated `GetModel` function from `groq/model.go`
- Update model validation cases to use new model constants in `groq/model.go`
- Update model mappings in `openai/openai.go` to reflect new model constants
- Adjust completion function in `openai/openai.go` to use new model strings
- Add new models to the allowed function call list in `openai/openai.go`
fix #154
> feat: update codebase to support new AI models

- cmd/commit.go
- openai/openai.go
- Add imports for "fmt" and "log" in `commit.go`
- Refactor message output to use a variable in `commit.go`
- Update error handling for completion response to check for both errors and the number of choices in `commit.go`
- Simplify the handling of summary prefix by removing conditional checks and replacing them with a single error check and assignment in `commit.go`
- Change `CreateFunctionCall` to accept a single `FunctionDefinition` instead of a variadic slice in `openai.go`
- Remove hardcoded system message content in `openai.go`
- Replace `Functions` field with `Tools` in `CreateFunctionCall` to use the new `Tool` struct in `openai.go`
- Remove specific function call strings from the allow list in `openai.go` and replace with a single entry
fix #156
> feat(api): switch func calling to tools

- cmd/commit.go
- Remove unused "fmt" import from commit.go
- Change error handling to display a message in red without exiting the function
- Add a condition to set `summaryPrix` based on `msg.Content` if no tool calls are found in the message
> feat: refactor error handling and output formatting

- README.md
- Add instructions for changing to ollama API Service
- Include usage examples for the `ollama` API Service
- Update the `base_url` in the config file without setting the `api_key`
fix https://github.com/appleboy/CodeGPT/issues/161
> docs: update ollama API Service integration and usage instructions

- cmd/commit.go
- openai/options.go
- openai/options_test.go
- Update condition check to use `String()` method for `openai.provider` in `commit.go`
- Replace constants `OPENAI` and `AZURE` with `Provider` type and add `String()` and `IsValid()` methods in `options.go`
- Modify `WithProvider` function to use `Provider` type and validate with `IsValid()` method in `options.go`
- Change `provider` field in `config` struct from `string` to `Provider` type in `options.go`
- Update `WithProvider` calls in `options_test.go` to use `String()` method for `Provider` type
ref: #153
> refactor(provider): handling in config system

- .golangci.yml
- cmd/commit.go
- cmd/hepler.go
- cmd/openai.go
- cmd/review.go
- git/git.go
- Add a new `.golangci.yml` configuration file with a list of linters and a 3-minute timeout setting
- Refactor `commit.go` to improve readability by breaking long lines of flag definitions
- Replace the OpenAI client initialization in `commit.go` with a call to a new function `NewOpenAI`
- Change file permission in `commit.go` from `644` to `600` when writing the `outputFile`
- Fix a typo in an error message in `hepler.go` (should be `helper.go`)
- Create a new `openai.go` file to handle OpenAI client initialization
- Remove OpenAI client initialization from `review.go` and replace it with a call to `NewOpenAI`
- Refactor `review.go` to improve readability by breaking long lines of flag definitions
- Update error messages in `git.go` to remove periods at the end
- Change file permission …
> build: refactor codebase and improve security

- .golangci.yml
- cmd/openai.go
- git/hook.go
- openai/openai.go
- openai/options.go
- prompt/prompt.go
- Remove linters `gochecknoinits` and `lll` from the `.golangci.yml` configuration
- Correct the case of the `WithApiVersion` function to `WithAPIVersion` in `openai.go` and `options.go`
- Suppress the `gochecknoinits` lint warning in `init` functions in `hook.go` and `prompt.go`
- Suppress the `gosec` lint warning for `InsecureSkipVerify` in `openai.go`
> style: refactor codebase and update linting rules

- cmd/commit.go
- core/openai.go
- core/platform.go
- openai/openai.go
- Add error handling for invalid provider in `commit.go`
- Replace `NewOpenAI` initialization with a switch case for different providers
- Simplify the summary prefix retrieval logic in `commit.go`
- Create a new `core/openai.go` file defining `Usage`, `Response`, and `Generative` interface
- Create a new `core/platform.go` file defining `Platform` type and its methods
- Implement `Completion` and `GetSummaryPrefix` methods in `openai.go` for the `core.Generative` interface
- Refactor `Completion` method to `completion` in `openai.go`
> refactor: provider handling and core interfaces

- cmd/openai.go
- openai/openai.go
- openai/options.go
- openai/options_test.go
- Update `WithProvider` to use `core.Platform` instead of a string
- Replace `Provider` type with `core.Platform`
- Remove `Provider` type and its associated methods
- Update test cases to use `core.Platform` constants
> refactor: use core.Platform instead of Provider type

- git/templates/prepare-commit-msg
When the generated message quality is not good, I use `codegpt commit --amend` to regenerate the message. 
**But there are still small parts that need to be modified manually.**
Using `git commit --amend` in the current version will cause the following error:
```
Error: please add your staged changes using git add <files...>
```
So I modified the `git/templates/prepare-commit-msg` file, so that `codegpt` is not executed when `git commit --amend` is used.
See the Git Hooks [documentation](https://git-scm.com/docs/githooks#_prepare_commit_msg)
> The second is the source of the commit message, and can be: message (if a -m or -F option was given); template (if a -t option was given or the configuration option commit.template is set); merge (if the commit is a merge or a .git/MERGE_MSG file …
> feat: ensure git commit --amend works with prepare-commit-msg hook

- README.md
Fix typo in Gemini API service section header.
> docs(readme): fix typo in Gemini API service section

- cmd/review.go
- Change `reviewCmd.Flags()` to `reviewCmd.PersistentFlags()`
- Add a new flag `prompt_only` to show the prompt without sending a request to OpenAI
- Modify error handling to check for `promptOnly` flag
- Add logic to display the prompt when `promptOnly` is set
fix https://github.com/appleboy/CodeGPT/issues/139
> feat: refactor command flags and add prompt-only mode

- cmd/hook.go
- Remove unused import of `errors`
- Add an `init` function to register `hookInstallCmd` and `hookUninstallCmd` commands
- Remove argument validation and error handling from `hookCmd`
- Introduce `hookInstallCmd` command for installing the prepare-commit-msg hook
- Introduce `hookUninstallCmd` command for uninstalling the prepare-commit-msg hook
fix https://github.com/appleboy/CodeGPT/issues/138
> feat: introduce hook management commands for git hooks

- cmd/commit.go
- cmd/textarea.go
- Add `tea` import from `github.com/charmbracelet/bubbletea`
- Trim commit message before displaying it
- Change confirmation prompt default to `Yes`
- Add prompt to change commit message with default `No`
- Add logic to handle commit message change using `bubbletea` program
- Create new file `textarea.go` for handling commit message input
- Implement `model` struct and functions for `textarea` interaction
- Add `View` function to display commit message confirmation prompt
fixed https://github.com/appleboy/CodeGPT/issues/146
> feat: implement commit message editing with bubbletea UI

- cmd/commit.go
- git/templates/prepare-commit-msg
- Add a `noConfirm` flag to skip the confirmation prompt
- Modify `commitCmd` to check for `noConfirm` flag in preview mode
- Update `prepare-commit-msg` template to include `--no_confirm` flag in `codegpt commit` command
fix #188
> feat: add noConfirm flag to streamline commit process

- cmd/openai.go
- gemini/gemini.go
- gemini/options.go
- Change the type of `maxTokens` from `int` to `int32` in multiple files
- Update the function `WithMaxTokens` to accept `int32` instead of `int`
- Adjust the usage of `maxTokens` in the `New` function to match the new type
> fix(gemini): refactor maxTokens type to int32 across the codebase

- git/templates/prepare-commit-msg
Hello, and thank you for this amazing product.
This pull request updates the shebang in a shell script that works with git hooks.
**Reason:**
POSIX sh does not support the `[[ ]]` syntax. 
The `[[ ]]` syntax works in bash and similar shells, but it is not supported by sh.
If the shell script is intended to work with bash, I recommend using the shebang `#!/usr/bin/env bash`.
Thank you for your consideration.
> chore: update shebang for prepare-commit-msg script

- prompt/templates/code_review_file_diff.tmpl
- prompt/templates/conventional_commit.tmpl
- prompt/templates/summarize_file_diff.tmpl
- prompt/templates/summarize_title.tmpl
- prompt/templates/translation.tmpl
- Correct typo "Bellow" to "Below" and improve sentence structure for clarity.
- Capitalize "CODE PATCH TO BE REVIEWED" for consistency.
- Fix grammatical errors and improve clarity in the conventional commit template.
- Correct "less" to "fewer" in the example summary comments.
- Fix grammatical error in the summarize file diff template.
- Change "high level" to "high-level" for consistency.
- Update character limit reminder from 50 to 60 characters.
- Ensure translation instructions emphasize high-level translation and formatting integrity.
Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>
> docs: improve grammar, clarity, and consistency in documentation

- cmd/commit.go
- cmd/openai.go
- cmd/review.go
- gemini/gemini.go
- Add context parameter to `GetClient` function in `commit.go`
- Import `context` package in `openai.go`
- Add context parameter to `NewGemini` function in `openai.go`
- Add context parameter to `GetClient` function in `openai.go`
- Add context parameter to `New` function in `gemini.go`
- Use provided context in `genai.NewClient` initialization in `gemini.go`
> refactor: add context support to client initialization functions

- cmd/provider.go
- core/platform.go
- provider/anthropic/options.go
- Rename `cmd/openai.go` to `cmd/provider.go`
- Add support for the Anthropic provider
- Add `NewAnthropic` function to create a new instance of `anthropic.Client`
- Update `GetClient` function to include the Anthropic platform
- Define `Anthropic` as a new platform constant
- Update `IsValid` function to include the Anthropic platform
- Change `WithModel` function parameter type from `anthropic.Model` to `string`
ref: #134
> feat: add support for Anthropic provider integration

- .gitignore
- provider/anthropic/anthropic.go
- provider/anthropic/func.go
- Add `.codegpt.yaml` to `.gitignore`
- Import `encoding/json` in `anthropic.go`
- Replace `MessageContentToolResult` with `MessageContentToolUse` in `GetSummaryPrefix` function
- Add JSON unmarshalling for `toolUse.Input` in `GetSummaryPrefix` function
- Change content assignment from `toolResult.Content[0].GetText()` to `result.Prefix` in `GetSummaryPrefix` function
- Define a new `tool` struct with a `Prefix` field in `func.go`
- Rename tool definition key from `unit` to `prefix` in `tools` slice
fix #134
> feat(anthropic): tool handling and improve summary prefix logic

- cmd/provider.go
- provider/anthropic/anthropic.go
- provider/anthropic/options.go
- Add support for proxy URL, SOCKS URL, and skip verify options in the Anthropic client configuration
- Introduce `DefaultHeaderTransport` to add custom headers to HTTP requests
- Add new HTTP transport configuration for handling proxy and SOCKS URLs
- Update the Anthropic client initialization to use the new HTTP client with custom transport
- Add `WithProxyURL`, `WithSocksURL`, and `WithSkipVerify` options for configuring the Anthropic client
> feat: add proxy and SOCKS5 support to HTTP Anthropic client

- provider/anthropic/anthropic.go
- Add proxy, socks, and skip verify options to the Anthropic client configuration
- Introduce `DefaultHeaderTransport` for adding headers to HTTP requests
- Implement HTTP client setup with optional proxy and SOCKS5 support
- Add new options `WithProxyURL`, `WithSocksURL`, and `WithSkipVerify` for client configuration
> docs: add proxy and SOCKS5 support to HTTP client configuration

- cmd/provider.go
- provider/anthropic/anthropic.go
- provider/anthropic/options.go
- provider/openai/openai.go
- proxy/options.go
- proxy/proxy.go
- Add timeout configuration option to `NewAnthropic` function
- Remove unused imports and replace `golang.org/x/net/proxy` with `github.com/appleboy/CodeGPT/proxy` in `anthropic.go`
- Refactor HTTP client creation to use new proxy package in `anthropic.go`
- Add `WithTimeout` option function in `options.go`
- Add `timeout` field to `config` struct in `options.go`
- Remove unused imports and replace `golang.org/x/net/proxy` with `github.com/appleboy/CodeGPT/proxy` in `openai.go`
- Refactor HTTP client creation to use new proxy package in `openai.go`
- Create new `proxy` package with options and proxy configuration functions
- Add `defaultHeaderTransport` for setting default headers in HTTP client in `proxy.go`
> feat: refactor HTTP client to use new proxy package with timeout options

- cmd/commit.go
- cmd/textarea.go
- Add a blank line for better readability in `commit.go`
- Change `textarea` field to be a pointer in `textarea.go`
- Update `textarea` initialization to use a pointer in `textarea.go`
- Modify `textarea` update method to dereference the pointer in `textarea.go`
> refactor: textarea handling to use pointer-based implementation

- provider/openai/openai.go
- Replace `checkO1Serial` with `checkOSeriesModels` for better matching of model strings
- Adjust regex pattern to `o\d((-mini|-preview))?`
> refactor: support o3 mini regex pattern for series models

- cmd/commit.go
- Improve commit preview confirmation logic.
- Fix https://github.com/appleboy/CodeGPT/issues/191
> Fix: commit preview confirmation behavior

- cmd/commit.go
- core/openai.go
- core/openai_test.go
- Replace manual token printing with a single usage string call
- Introduce a method that handles token counts and their details
- Add tests verifying the usage string output in various scenarios
> feat: consolidate token usage and test coverage

- provider/openai/openai.go
The function call of Deepseek-V3 is currently encountering problems, making it unable to work with tool calls. See [doc](https://api-docs.deepseek.com/guides/function_calling#notice).
Fortunately, Deepseek-V3 operates correctly when using the ChatCompletion method, similar to OpenAI's models with the pattern `o\d(-(mini|preview))?`. This pull request aims to implement this solution.
This pull request includes the necessary modifications to ensure that Deepseek-V3 can function properly with tool calls by utilizing the ChatCompletion method.
The changes have been thoroughly tested to ensure compatibility and functionality with tool calls.
Please review the proposed changes and provide your approval to proceed with the integration.
> fix(azure): function call issues in deepseek-V3

- cmd/cmd.go
- cmd/hepler.go
- cmd/prompt.go
- prompt/prompt.go
- util/template.go
- util/template_test.go
- Add `promptFolder` variable and setting it via command line flag
- Create and validate `promptFolder` during configuration initialization
- Implement loading of custom prompt templates from `promptFolder`
- Implement the `prompt` command to load default prompt data
- Add function to get raw data of the template
- Initialize `templates` as an empty map to avoid redundant checks
- Add support to load templates from a specified directory
- Add tests for loading templates from a directory
fix https://github.com/appleboy/CodeGPT/issues/142
fix https://github.com/appleboy/CodeGPT/issues/216
> feat: add support for customizable prompt templates from directories

- cmd/cmd.go
- cmd/config_list.go
- cmd/config_set.go
- cmd/hepler.go
- cmd/prompt.go
- Add detailed comments to the `initConfig` function to describe its steps and purpose
- Replace existing logic for handling the prompt folder with a switch-case structure
- Add `prompt.folder` configuration key to the list of available keys
- Add `prompt.folder` flag to `configSetCmd`
- Update the configuration key `prompt_folder` to `prompt.folder` in `helper.go`
- Enhance `prompt.go` to display the prompt folder path and improve confirmation prompt message
fix #226
> feat: refactor prompt folder handling and update its configuration key

- README.md
- README.zh-tw.md
- Add support for customizing prompt templates and variables
- Introduce `prompt.folder` configuration with a default location
- Add detailed instructions on how to customize the default prompt folder
- Update OpenAI model configuration value from `gpt-35-turbo` to `gpt-4o`
fix #227 
fix #225
> docs(readme): add support for customizable prompt templates

- README.md
Add [mention](https://github.com/kvokka/features/tree/main/src/codegpt) about vscode devcontainer feature, which I already created for this tool
> docs: add vscode devcontainer to readme

- Makefile
- cmd/version.go
- go.mod
- version/version.go
- Expand embedded build-time variables to include Git commit, build time, Go version, operating system, and architecture
- Update build process to inject additional version and environment metadata
- Improve version command to output detailed build information, support both text and JSON formats, and add colored CLI output
- Update Go version requirement to 1.24 in go.mod
> build: enhance build metadata and version reporting functionality

- core/transport/headers_test.go
- core/transport/transport_test.go
- Add tests for parsing header strings into http.Header, covering normal input, invalid format, duplicate keys, and empty/nil input
- Add tests for DefaultHeaderTransport to verify attaching custom headers, handling empty app info, propagating errors, and supporting multiple header values
> test: add comprehensive tests for HTTP header parsing and transport

- install.sh
- Add a shell script for installing the CodeGPT CLI with automatic OS and architecture detection
- Download and install the appropriate CodeGPT binary and set executable permissions
- Append the CodeGPT installation directory to PATH in the user's shell config file based on detected shell
- Include error handling for unsupported platforms or architectures and for missing shell config files
- Provide colored terminal output and informative error and status messages
fixed https://github.com/appleboy/CodeGPT/pull/206
> feat: add automated cross-platform install script for CodeGPT CLI
